# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoDialog.ui'
#
# Created: Tue May 24 13:38:09 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_InfoDialog(object):
    def setupUi(self, InfoDialog):
        InfoDialog.setObjectName("InfoDialog")
        InfoDialog.resize(343, 261)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InfoDialog.sizePolicy().hasHeightForWidth())
        InfoDialog.setSizePolicy(sizePolicy)
        InfoDialog.setMinimumSize(QtCore.QSize(343, 261))
        InfoDialog.setMaximumSize(QtCore.QSize(343, 261))
        self.verticalLayout_3 = QtGui.QVBoxLayout(InfoDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wordLabel = QtGui.QLabel(InfoDialog)
        self.wordLabel.setObjectName("wordLabel")
        self.horizontalLayout.addWidget(self.wordLabel)
        self.wordLineEdit = QtGui.QLineEdit(InfoDialog)
        self.wordLineEdit.setObjectName("wordLineEdit")
        self.horizontalLayout.addWidget(self.wordLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.meaningsLabel = QtGui.QLabel(InfoDialog)
        self.meaningsLabel.setObjectName("meaningsLabel")
        self.horizontalLayout_2.addWidget(self.meaningsLabel)
        self.meaningsLineEdit = QtGui.QLineEdit(InfoDialog)
        self.meaningsLineEdit.setObjectName("meaningsLineEdit")
        self.horizontalLayout_2.addWidget(self.meaningsLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.contextLabel = QtGui.QLabel(InfoDialog)
        self.contextLabel.setObjectName("contextLabel")
        self.horizontalLayout_3.addWidget(self.contextLabel)
        self.contextLineEdit = QtGui.QLineEdit(InfoDialog)
        self.contextLineEdit.setObjectName("contextLineEdit")
        self.horizontalLayout_3.addWidget(self.contextLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.difficultyLabel = QtGui.QLabel(InfoDialog)
        self.difficultyLabel.setObjectName("difficultyLabel")
        self.horizontalLayout_4.addWidget(self.difficultyLabel)
        self.difficultyComboBox = QtGui.QComboBox(InfoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.difficultyComboBox.sizePolicy().hasHeightForWidth())
        self.difficultyComboBox.setSizePolicy(sizePolicy)
        self.difficultyComboBox.setMinimumSize(QtCore.QSize(95, 0))
        self.difficultyComboBox.setObjectName("difficultyComboBox")
        self.difficultyComboBox.addItem("")
        self.difficultyComboBox.addItem("")
        self.difficultyComboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.difficultyComboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.groupBox = QtGui.QGroupBox(InfoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.askedLabel = QtGui.QLabel(self.groupBox)
        self.askedLabel.setObjectName("askedLabel")
        self.verticalLayout.addWidget(self.askedLabel)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.answeredLabel = QtGui.QLabel(self.groupBox)
        self.answeredLabel.setObjectName("answeredLabel")
        self.horizontalLayout_5.addWidget(self.answeredLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.addedLabel = QtGui.QLabel(InfoDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addedLabel.sizePolicy().hasHeightForWidth())
        self.addedLabel.setSizePolicy(sizePolicy)
        self.addedLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.addedLabel.setObjectName("addedLabel")
        self.horizontalLayout_6.addWidget(self.addedLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.closeButton = QtGui.QPushButton(InfoDialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_6.addWidget(self.closeButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.wordLabel.setBuddy(self.wordLineEdit)
        self.meaningsLabel.setBuddy(self.meaningsLineEdit)
        self.contextLabel.setBuddy(self.contextLineEdit)
        self.difficultyLabel.setBuddy(self.difficultyComboBox)

        self.retranslateUi(InfoDialog)
        QtCore.QMetaObject.connectSlotsByName(InfoDialog)

    def retranslateUi(self, InfoDialog):
        InfoDialog.setWindowTitle(QtGui.QApplication.translate("InfoDialog", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.wordLabel.setText(QtGui.QApplication.translate("InfoDialog", "Word: ", None, QtGui.QApplication.UnicodeUTF8))
        self.meaningsLabel.setText(QtGui.QApplication.translate("InfoDialog", "Meanings: ", None, QtGui.QApplication.UnicodeUTF8))
        self.contextLabel.setText(QtGui.QApplication.translate("InfoDialog", "Context: ", None, QtGui.QApplication.UnicodeUTF8))
        self.difficultyLabel.setText(QtGui.QApplication.translate("InfoDialog", "Difficulty: ", None, QtGui.QApplication.UnicodeUTF8))
        self.difficultyComboBox.setItemText(0, QtGui.QApplication.translate("InfoDialog", "EASY", None, QtGui.QApplication.UnicodeUTF8))
        self.difficultyComboBox.setItemText(1, QtGui.QApplication.translate("InfoDialog", "MEDIUM", None, QtGui.QApplication.UnicodeUTF8))
        self.difficultyComboBox.setItemText(2, QtGui.QApplication.translate("InfoDialog", "HARD", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("InfoDialog", "How many times was it..", None, QtGui.QApplication.UnicodeUTF8))
        self.askedLabel.setText(QtGui.QApplication.translate("InfoDialog", "..asked: ", None, QtGui.QApplication.UnicodeUTF8))
        self.answeredLabel.setText(QtGui.QApplication.translate("InfoDialog", "..answered: ", None, QtGui.QApplication.UnicodeUTF8))
        self.addedLabel.setText(QtGui.QApplication.translate("InfoDialog", "Added on: ", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("InfoDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

