# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestDialog.ui'
#
# Created: Tue Apr  5 23:35:30 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_testDialog(object):
    def setupUi(self, testDialog):
        testDialog.setObjectName("testDialog")
        testDialog.resize(387, 180)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(testDialog.sizePolicy().hasHeightForWidth())
        testDialog.setSizePolicy(sizePolicy)
        testDialog.setMinimumSize(QtCore.QSize(387, 0))
        testDialog.setMaximumSize(QtCore.QSize(10000, 10000))
        self.verticalLayout_2 = QtGui.QVBoxLayout(testDialog)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(testDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.wordLabel = QtGui.QLabel(testDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordLabel.sizePolicy().hasHeightForWidth())
        self.wordLabel.setSizePolicy(sizePolicy)
        self.wordLabel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.wordLabel.setScaledContents(True)
        self.wordLabel.setObjectName("wordLabel")
        self.horizontalLayout_2.addWidget(self.wordLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(testDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.answerLineEdit = HtmlLineEdit(testDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answerLineEdit.sizePolicy().hasHeightForWidth())
        self.answerLineEdit.setSizePolicy(sizePolicy)
        self.answerLineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.answerLineEdit.setMaximumSize(QtCore.QSize(16777215, 27))
        self.answerLineEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.answerLineEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.answerLineEdit.setObjectName("answerLineEdit")
        self.horizontalLayout.addWidget(self.answerLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pointsLabel = QtGui.QLabel(testDialog)
        self.pointsLabel.setObjectName("pointsLabel")
        self.horizontalLayout_3.addWidget(self.pointsLabel)
        self.showContextCheckBox = QtGui.QCheckBox(testDialog)
        self.showContextCheckBox.setObjectName("showContextCheckBox")
        self.horizontalLayout_3.addWidget(self.showContextCheckBox)
        self.okButton = QtGui.QPushButton(testDialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_3.addWidget(self.okButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.contextFrame = QtGui.QFrame(testDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contextFrame.sizePolicy().hasHeightForWidth())
        self.contextFrame.setSizePolicy(sizePolicy)
        self.contextFrame.setMinimumSize(QtCore.QSize(0, 56))
        self.contextFrame.setMaximumSize(QtCore.QSize(16777215, 56))
        self.contextFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.contextFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.contextFrame.setObjectName("contextFrame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.contextFrame)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.contextLineEdit = QtGui.QTextEdit(self.contextFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contextLineEdit.sizePolicy().hasHeightForWidth())
        self.contextLineEdit.setSizePolicy(sizePolicy)
        self.contextLineEdit.setMinimumSize(QtCore.QSize(0, 54))
        self.contextLineEdit.setMaximumSize(QtCore.QSize(16777215, 54))
        self.contextLineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.contextLineEdit.setAcceptDrops(False)
        self.contextLineEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.contextLineEdit.setUndoRedoEnabled(False)
        self.contextLineEdit.setReadOnly(True)
        self.contextLineEdit.setObjectName("contextLineEdit")
        self.horizontalLayout_4.addWidget(self.contextLineEdit)
        self.verticalLayout_2.addWidget(self.contextFrame)

        self.retranslateUi(testDialog)
        QtCore.QMetaObject.connectSlotsByName(testDialog)

    def retranslateUi(self, testDialog):
        testDialog.setWindowTitle(QtGui.QApplication.translate("testDialog", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("testDialog", "Word:", None, QtGui.QApplication.UnicodeUTF8))
        self.wordLabel.setText(QtGui.QApplication.translate("testDialog", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("testDialog", "Answer:", None, QtGui.QApplication.UnicodeUTF8))
        self.pointsLabel.setText(QtGui.QApplication.translate("testDialog", "Points: 999/999", None, QtGui.QApplication.UnicodeUTF8))
        self.showContextCheckBox.setText(QtGui.QApplication.translate("testDialog", "Show context", None, QtGui.QApplication.UnicodeUTF8))
        self.okButton.setText(QtGui.QApplication.translate("testDialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))

from HtmlLineEdit import HtmlLineEdit
